# Generated by Django 5.2.3 on 2025-08-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_stock_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
