# Generated by Django 5.2.3 on 2025-07-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='comflit',
        ),
    ]
