# Generated by Django 5.2.3 on 2025-07-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='user/images'),
            preserve_default=False,
        ),
    ]
