# Generated by Django 5.2.3 on 2025-07-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_quantity_remove_orderitem_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
